language: python

python:
    - 3.6

env:
    - DJANG0=1.11b

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    coverage run --source=lists,accounts manage.py test lists accounts

after_success:
    coveralls

branches:
    only:
        - master
